---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# targets.utils

<!-- badges: start -->
<!-- badges: end -->

Some simple utility functions for interactively writing and running targets pipelines.

## Installation

You can install the development version of targets.utils from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("geryan/targets.utils")
```

```{r}
library(targets)

tar_dir({

  # tar_dir() runs code from a temporary directory.

  tar_script({

    library(targets)
    library(geotargets)
    library(terra)
    library(tibble)
    library(targets.utils)

    make_nested_object <- function() {

      r <- terra::rast(
        system.file("ex", "elev.tif", package = "terra")
      )

      v <- terra::vect(
        system.file("ex", "lux.shp", package = "terra")
      )

      list(
        raster = r,
        vector = v,
        metadata = tibble(
          dataset = "example",
          n_cells = terra::ncell(r),
          n_features = nrow(v)
        )
      )
    }

    list(

      tar_terra_nested(
        nested_spatial,
        make_nested_object()
      )

    )
  })

  tar_make()

  x <- tar_read(nested_spatial)

  x

})
```

